app1:
  build: app/
  command: python app.py
  ports:
   - "5001:5000"
  volumes:
   - app/:/code
  links:
   - redis

app2:
  build: app/
  command: python app.py
  ports:
   - "5002:5000"
  volumes:
   - app/:/code
  links:
   - redis

hipache:
  image: tutum/hipache
  ports:
   - "9090:80"

redis:
  image: redis
